### ISSUE TITLE
fix: live code editor extra user when exiting the page

### ISSUE THREAD

**Issue by sltsheryl** [CS3219-AY2324S1/ay2324s1-course-assessment-g17#83]

**Comment by chloeelim** [comment]
fixed in https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/pull/92

**Comment by sltsheryl** [comment]
> fixed in #92

@chloeelim err im not sure if it was fixed, i think i saw it still happening

**Comment by chloeelim** [comment]
> > fixed in #92
> 
> @chloeelim err im not sure if it was fixed, i think i saw it still happening

oh woops can't seem to replicate it, hm... will take a look again! i think i can change it to use socket.io but there might be issues syncing with the code editor markers
